:_newdoc-version: 2.15.0
:_template-generated: 2023-11-6
:_mod-docs-content-type: PROCEDURE

[id="testing-an-application-deployed-to-server-on-cloudplaform_{context}"]
= Testing an application deployed to {ProductShortname} on {cloudPlatform}

[role="_abstract"]
Create an integration test that verifies that the application is deployed and running on {ProductShortName} on {cloudPlatform}, by checking that the HTTP GET of its web page returns 200 OK.

In this procedure, _<application_home>_ refers to the directory that contains the `pom.xml` configuration file for the application.

If you have already added the test class, proceed to step 6.


.Prerequisites

* You have deployed your application to {ProductShortname} on {cloudPlatform}.
* You have added the Maven dependencies required for JUnit tests.


.Procedure

include::fragments/frag_testing-an-application.adoc[]

. Push the changes to your repository.
+
[source,options="nowrap"]
----
$ git add --all
$ git commit -m "add test class to the application"
$ git push HEAD
----

.Verification

. Navigate to the _<application_home>_ directory.
. Run the test by using the `vefiry` command, activating the `integration-testing` profile and specifying the URL to the application.
+
[source,options="nowrap"]
----
$ mvn verify -Pintegration-testing -Dserver.host=https://$(oc get route {helm-app-name} --template='{{ .spec.host }}')
----
