:_content-type: PROCEDURE

:QS-path: {helloworld-QS-path}

[id="creating-a-maven-project-for-a-simple-web-application_{context}"]
= Creating a Maven project for a web application

Create a Maven project by using the `maven-archetype-webapp` archetype to get started with building web-applications for {ProductShortname} deployment. Maven provides different archetypes to create projects based on templates specific to different project types. The `maven-archetype-webapp` creates a project with the structure required to develop simple web-applications.

.Prerequisites

* You have installed Maven. For more information, see link:https://maven.apache.org/download.cgi[Downloading Apache Maven].

.Procedure

. Set up a Maven project using the `mvn` command. The command creates the directory structure for the project and the `pom.xml` configuration file.
+
[source,options="nowrap",subs="attributes+"]
----
$ mvn archetype:generate                          \
-DgroupId={helloworld-QS-groupId}                \// <1>
-DartifactId={helloworld-QS-artifactId}                           \// <2>
-DarchetypeGroupId=org.apache.maven.archetypes    \// <3>
-DarchetypeArtifactId=maven-archetype-webapp      \// <4>
-DinteractiveMode=false                            // <5>
----
<1> `groupID` uniquely identifies the project.
<2> `artifcatID` is the name for the generated jar.
<3> The `groupID` of `maven-archetype-webapp`.
<4> `maven-archetype-webapp`
<5> Tell Maven to use use the supplied parameters instead of starting interactive mode.

. Navigate to the application root directory:
+
[source,options="nowrap",subs=attributes]
----
$ cd {helloworld-QS-artifactId}
----

. Update the content of the generated `pom.xml`.

.. Remove the content inside the `<project>` section after the `<url>\http://www.example.com</url>` line.
+
Add the following elements in the `<project>` section.


.. Define the following properties for the project. You can use the values defined in the __<property>__ element throughout the project by using the ${__<property>__} syntax.
+
[source,xml,options="nowrap",subs=attributes+]
----
<properties>
    <version.server>{JBossServerBOMVersion}</version.server>                    <!--1-->
    <version.bom.ee>${version.server}</version.bom.ee>           <!--2-->
</properties>
----
+
<1> `<version.server>` defines the {ProductShortname} release version for which the application is being created.
<2> `<version.bom.ee>` defines the {ProductShortname} BOM version to use.

.. Define the repositories in which Maven looks for artifacts to download in these repositories.
+
Defining repositories in the POM is a convenience feature. To speed up build in a production environment, define the repositories in `settings.xml` instead.
+
[source,xml,options="nowrap"]
----
<repositories>
    <repository>                                                                <!--1-->
        <id>jboss-public-maven-repository</id>
        <name>JBoss Public Maven Repository</name>
        <url>https://repository.jboss.org/nexus/content/groups/public/</url>
        <releases>
             <enabled>true</enabled>
             <updatePolicy>never</updatePolicy>
         </releases>
         <snapshots>
             <enabled>true</enabled>
             <updatePolicy>never</updatePolicy>
         </snapshots>
             <layout>default</layout>
    </repository>
    <repository>                                                                <!--2-->
        <id>redhat-ga-maven-repository</id>
        <name>Red Hat GA Maven Repository</name>
        <url>https://maven.repository.redhat.com/ga/</url>
        <releases>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
        </releases>
        <snapshots>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
        </snapshots>
        <layout>default</layout>
    </repository>
</repositories>
----
<1> TODO: Add description of the repository.
<2> TODO: Add description of the repository.
+

.. Define the repositories in which Maven looks for plug-ins to download in these repositories.
+
Defining repositories in the POM is a convenience feature. To speed up build in a production environment, define the repositories in `settings.xml` instead.
+
[source,xml,options="nowrap"]
----
<pluginRepositories>
    <pluginRepository>                                                               <!--1-->
        <id>jboss-public-maven-repository</id>
        <name>JBoss Public Maven Repository</name>
        <url>https://repository.jboss.org/nexus/content/groups/public/</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
    <pluginRepository>                                                               <!--2-->
        <id>redhat-ga-maven-repository</id>
        <name>Red Hat GA Maven Repository</name>
        <url>https://maven.repository.redhat.com/ga/</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
                <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
----
<1> TODO: Add description of the repository.
<2> TODO: Add description of the repository.

.. Specify the {ProductShortname} {JEEE} spec BOM to control the versions of runtime Maven dependencies. When you specify a BOM in the `<dependencyManagement>` section, you do not need to individually specify the versions of the Maven dependencies defined in the `provided` scope.
+
[source,xml,options="nowrap",subs=attributes+]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>{JBossGroupID}</groupId>                 <!--1-->
            <artifactId>{JBossEAPBOMWithTools}</artifactId> <!--2-->
            <version>${version.bom.ee}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----
<1> GroupID of the {ProductShortname}-provided BOM.
<2> ArtifactID of the {ProductShortname}-provided BOM that provides supported {ProductShortname} {JEE} APIs plus additional {ProductShortname} API JARs and client BOMs, and development tools such as Arquillian.


.Verification

* In the application root directory, enter the following command to download the Maven dependencies:
+
[source,options="nowrap"]
----
$ mvn install
----
+
You get an output similar to the following:
+
[source,options="nowrap"]
----
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
...
----

.Next Steps
* xref:creating-a-servlet-with-cdi_creating-a-hello-world-application-with-servlet-and-cdi[Creating a Servlet with CDI]
