:_content-type: PROCEDURE

[id="deploying-an-application-to-a-bare-metal-installation_{context}"]
= Deploying an application to a bare metal installation

[role="_abstract"]
You can deploy an application to {ProductShortname} by using the {ProductShortname} deploy plugin.

.Prerequisites

* You have created an application.
+
For more information, see xref:creating-a-hello-world-servlet_default[Creating a hello world servlet].
* {ProductShortname} is running.

.Procedure

. Navigate to the application root directory.
+
The application root directory contains the `pom.xml` configuration file.


. Add the following build configuration to the `pom.xml` configuration file in the `<project>` section to define the application archive filename.
+
[source,xml,options="nowrap"]
----
<build>
...
  <finalName>${project.artifactId}</finalName>        <!--1-->
</build>
----
<1> Set the name of the deployment to the project's artifact ID.

. Build and deploy the application by using the {ProductShortName} deploy plugin.
+
[source,options="nowrap"]
----
$ mvn package wildfly:deploy
----

.Verification

* Navigate to the address `http://localhost:8080/{helloworld-QS-artifactId}/HelloWorld` in a browser.
+
You get the following message:
+
----
Hello World!
----
