:_newdoc-version: 2.15.0
:_template-generated: 2023-11-21
:_mod-docs-content-type: PROCEDURE

[id="creating-a-maven-project-with-the-webapp-maven-archetype_{context}"]
= Creating a Maven project with `maven-archetype-webapp`

[role="_abstract"]
Use the `maven-archetype-webapp` archetype to create a Maven project for building applications for {ProductShortName} deployment. Maven provides different archetypes for creating projects based on templates specific to project types. The `maven-archetype-webapp` creates a project with the structure required to develop simple web-applications.

.Prerequisites

* You have installed Maven. For more information, see link:https://maven.apache.org/download.cgi[Downloading Apache Maven].


.Procedure

. Set up a Maven project by using the `mvn` command. The command creates the directory structure for the project and the `pom.xml` configuration file.
+
[source,options="nowrap",subs="attributes+"]
----
$ mvn archetype:generate                          \
-DgroupId={helloworld-QS-groupId}                \// <1>
-DartifactId={helloworld-QS-artifactId}                           \// <2>
-DarchetypeGroupId=org.apache.maven.archetypes    \// <3>
-DarchetypeArtifactId=maven-archetype-webapp      \// <4>
-DinteractiveMode=false                            // <5>
----
<1> `groupID` uniquely identifies the project.
<2> `artifactID` is the name for the generated `jar` archive.
<3> The `groupID` of `maven-archetype-webapp`.
<4> The `artifactID` of `maven-archetype-webapp`.
<5> Tell Maven to use the supplied parameters rather than starting interactive mode.

. Navigate to the generated directory.
+
[source,options="nowrap",subs="attributes+"]
----
$ cd {helloworld-QS-artifactId}
----

. Open the generated `pom.xml` configuration file in a text editor.

. Remove the content inside the `<project>` section of `pom.xml` configuration file  after the `<name>helloworld Maven Webapp</name>` line. 
+
Ensure that the file looks like this:
+
[source,xml,options="nowrap"]
----
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.jboss.as.quickstarts</groupId>
  <artifactId>helloworld</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>war</packaging>

  <name>helloworld Maven Webapp</name>
  
</project>
----
+
The content was removed because it is not required for the application.

[role="_additional-resources"]
.Next steps

* xref:defining-properties-in-a-maven-project_creating-a-maven-project-for-a-hello-world-application[Defining properties in Maven project for a JBoss EAP hello world application]. 

